name: Extract
 
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

env:
  ROM_URL: https://cdnsamfw14.space/v2/IxJCDiMnLhcSJAU5LwsHQR47OzkuMR4lFzssIDs2ByAzMUEgOzEUQDMQMCMBOyw/NRcHKR4nFAkyJB4JNScULzU7LgANQCANHhcHGhIxND88MTM8LgsjJB4nLBIPOCAkEhEaOQMHQRsyCyktMi8eGxIHIzE0Fy4FNBdBOQMsBQYXJUErHjEuPyMbBkIjCyI/Iws8MQEWCDAeCw0xCREHOTQbIyshAD4OIQAGLC44Hiw0ER4OMiUzLDIlDSs8AD4fJhsGOg8HCkA8AywnCRc+Di8LBxAzBy4RDxYpKTwkHjUeBylCJgceKTIXIUAJER4OMi8+AwMSMDoeJCIGAy8zJhcsMxw4MQpAIxYHHi8HITovO0EWLzs8PzgAISk8PxQ9NTggQiYnHz8hJDs5AzsvHjQvAiEvBzs/LicwHDUvBx81FiE/NBszFA0RKQAyQCE5IzgGQiMDPDAeCw0kIwMIBh4iExM=

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Firmware Extractor
         run: |
              git clone --recurse-submodules https://github.com/AndroidDumps/Firmware_extractor.git
       - name: Setup extractor environment
         working-directory: Firmware_extractor
         run: |
              sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract rename
              sudo apt install liblzma-dev python3 python3-dev python3-pip brotli lz4 aria2
              pip3 install backports.lzma protobuf pycrypto twrpdtgen extract-dtb
       - name: Running Firmware Extractor
         working-directory: Firmware_extractor
         run: |
              aria2c -x16 -j$(nproc) -U "Mozilla/5.0" -o "FIRMWARE.tgz" "$ROM_URL"
              ./extractor.sh FIRMWARE.tgz
       - name: Store extracted firmware
         uses: actions/upload-artifact@v2
         with:
           name: FIRMWARE
           path: |
