name: Building Twrp recovery Android 4-10

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  tested on android 8.1
  workflow_dispatch:

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
  DEVICE: gts7l
  DT_LINK: https://github.com/ianmacd/twrp_gts7l
  DT_PATH: device/samsung/gts7l
  TARGET: recovery
  TZ: Europe/London

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: Initializing environment
         run: |
             echo ${{ secrets.TELEGRAM_TOKEN }}
